package plugin

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Scaffold generates a starter plugin project with main.go, generator.go,
// go.mod, Makefile, and README.md.
func Scaffold(name, category, outputDir string) error {
	if name == "" {
		return fmt.Errorf("plugin name is required")
	}

	// Validate category.
	switch category {
	case "frontend", "backend", "database", "infra":
		// ok
	default:
		return fmt.Errorf("invalid category %q: must be frontend, backend, database, or infra", category)
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	moduleName := fmt.Sprintf("github.com/user/human-plugin-%s", name)

	files := map[string]string{
		"main.go":      scaffoldMain(name, category),
		"generator.go": scaffoldGenerator(name, category),
		"go.mod":       scaffoldGoMod(moduleName),
		"Makefile":     scaffoldMakefile(name),
		"README.md":    scaffoldReadme(name, category),
	}

	for filename, content := range files {
		path := filepath.Join(outputDir, filename)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", filename, err)
		}
	}

	return nil
}

func scaffoldMain(name, category string) string {
	return fmt.Sprintf(`package main

import (
	"encoding/json"
	"fmt"
	"os"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: %s <meta|generate> [flags]")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "meta":
		meta := map[string]string{
			"name":        %q,
			"version":     "0.1.0",
			"description": "%s code generator plugin",
			"category":    %q,
		}
		json.NewEncoder(os.Stdout).Encode(meta)
	case "generate":
		if err := runGenerate(os.Args[2:]); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %%s\n", os.Args[1])
		os.Exit(1)
	}
}
`, name, name, strings.Title(name), category)
}

func scaffoldGenerator(name, category string) string {
	return fmt.Sprintf(`package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
)

func runGenerate(args []string) error {
	fs := flag.NewFlagSet("generate", flag.ExitOnError)
	irFile := fs.String("ir", "", "Path to IR JSON file")
	outputDir := fs.String("output", "", "Output directory")
	settings := fs.String("settings", "", "Plugin settings JSON")
	fs.Parse(args)

	if *irFile == "" || *outputDir == "" {
		return fmt.Errorf("--ir and --output are required")
	}

	// Read the IR.
	data, err := os.ReadFile(*irFile)
	if err != nil {
		return fmt.Errorf("reading IR: %%w", err)
	}

	var app map[string]interface{}
	if err := json.Unmarshal(data, &app); err != nil {
		return fmt.Errorf("parsing IR: %%w", err)
	}

	// Parse settings if provided.
	var pluginSettings map[string]string
	if *settings != "" {
		if err := json.Unmarshal([]byte(*settings), &pluginSettings); err != nil {
			return fmt.Errorf("parsing settings: %%w", err)
		}
	}

	// Create output directory.
	if err := os.MkdirAll(*outputDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %%w", err)
	}

	// TODO: Generate your %s code here.
	// The IR contains the full application specification.
	// Write generated files to outputDir.

	appName, _ := app["name"].(string)
	if appName == "" {
		appName = "app"
	}

	content := fmt.Sprintf("// Generated by %s plugin for %%s\n", appName)
	outPath := filepath.Join(*outputDir, "generated.txt")
	return os.WriteFile(outPath, []byte(content), 0644)
}
`, category, name)
}

func scaffoldGoMod(moduleName string) string {
	return fmt.Sprintf(`module %s

go 1.25
`, moduleName)
}

func scaffoldMakefile(name string) string {
	return fmt.Sprintf(`.PHONY: build test install clean

build:
	go build -o %s .

test:
	go test ./... -count=1

install: build
	human plugin install --binary ./%s

clean:
	rm -f %s
`, name, name, name)
}

func scaffoldReadme(name, category string) string {
	return fmt.Sprintf(`# human-plugin-%s

A Human compiler plugin for %s code generation.

## Category

%s

## Quick Start

`+"```"+`bash
# Build the plugin
make build

# Install into Human
make install
# or
human plugin install --binary ./%s

# Verify installation
human plugin list
`+"```"+`

## Protocol

This plugin communicates with the Human compiler via two subcommands:

- `+"`%s meta`"+` — prints plugin metadata as JSON
- `+"`%s generate --ir <path> --output <dir>`"+` — generates code from IR

## Development

`+"```"+`bash
# Build
make build

# Test
make test

# Run meta manually
./%s meta

# Run generate manually
./%s generate --ir path/to/ir.json --output ./out
`+"```"+`
`, name, category, category, name, name, name, name, name)
}
