#!/bin/bash
# Mock plugin binary for testing the external plugin adapter.
# Supports: meta, generate

case "$1" in
  meta)
    cat <<'EOF'
{
  "name": "mock-plugin",
  "version": "0.1.0",
  "description": "A mock plugin for testing",
  "category": "frontend"
}
EOF
    ;;
  generate)
    # Parse --ir and --output flags
    IR_FILE=""
    OUTPUT_DIR=""
    SETTINGS=""
    shift
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --ir) IR_FILE="$2"; shift 2 ;;
        --output) OUTPUT_DIR="$2"; shift 2 ;;
        --settings) SETTINGS="$2"; shift 2 ;;
        *) shift ;;
      esac
    done

    if [[ -z "$IR_FILE" || -z "$OUTPUT_DIR" ]]; then
      echo "missing --ir or --output" >&2
      exit 1
    fi

    # Verify IR file exists and is valid JSON
    if [[ ! -f "$IR_FILE" ]]; then
      echo "IR file not found: $IR_FILE" >&2
      exit 1
    fi

    # Create output
    mkdir -p "$OUTPUT_DIR"
    echo "<!-- Generated by mock-plugin -->" > "$OUTPUT_DIR/index.html"

    # Copy IR to output for round-trip verification
    cp "$IR_FILE" "$OUTPUT_DIR/ir-copy.json"

    # If settings were provided, write them too
    if [[ -n "$SETTINGS" ]]; then
      echo "$SETTINGS" > "$OUTPUT_DIR/settings.json"
    fi
    ;;
  *)
    echo "unknown command: $1" >&2
    exit 1
    ;;
esac
