package quality

import (
	"fmt"
	"strings"

	"github.com/barun-bash/human/internal/ir"
)

// generateSecurityTests produces a standalone bash script that uses curl to probe
// a running application for 7 vulnerability categories. Returns the script content
// and total test count.
func generateSecurityTests(app *ir.Application) (string, int) {
	if len(app.APIs) == 0 {
		return "", 0
	}

	var b strings.Builder
	count := 0

	writeScriptHeader(&b)
	writeHelperFunctions(&b)

	count += writeAuthBypassTests(&b, app)
	count += writeSQLInjectionTests(&b, app)
	count += writeXSSTests(&b, app)
	count += writeValidationBypassTests(&b, app)
	count += writeIDORTests(&b, app)
	count += writeRateLimitTests(&b, app)
	count += writeCORSTests(&b, app)

	writeScriptFooter(&b, count)

	return b.String(), count
}

// writeScriptHeader writes the shebang, argument parsing, and counters.
func writeScriptHeader(b *strings.Builder) {
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Security test script — generated by Human compiler\n")
	b.WriteString("# Usage: ./security-tests.sh <BASE_URL> [AUTH_TOKEN]\n")
	b.WriteString("set -euo pipefail\n\n")
	b.WriteString("BASE_URL=\"${1:?Usage: $0 <BASE_URL> [AUTH_TOKEN]}\"\n")
	b.WriteString("AUTH_TOKEN=\"${2:-}\"\n")
	b.WriteString("PASS=0\nFAIL=0\nTOTAL=0\n\n")
}

// writeHelperFunctions writes the assert_status and assert_not_status bash helpers.
func writeHelperFunctions(b *strings.Builder) {
	b.WriteString("assert_status() {\n")
	b.WriteString("  local desc=\"$1\" expected=\"$2\" actual=\"$3\"\n")
	b.WriteString("  TOTAL=$((TOTAL + 1))\n")
	b.WriteString("  if [ \"$actual\" -eq \"$expected\" ]; then\n")
	b.WriteString("    PASS=$((PASS + 1))\n")
	b.WriteString("    echo \"  PASS: $desc\"\n")
	b.WriteString("  else\n")
	b.WriteString("    FAIL=$((FAIL + 1))\n")
	b.WriteString("    echo \"  FAIL: $desc (expected $expected, got $actual)\"\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n\n")

	b.WriteString("assert_not_status() {\n")
	b.WriteString("  local desc=\"$1\" rejected=\"$2\" actual=\"$3\"\n")
	b.WriteString("  TOTAL=$((TOTAL + 1))\n")
	b.WriteString("  if [ \"$actual\" -ne \"$rejected\" ]; then\n")
	b.WriteString("    PASS=$((PASS + 1))\n")
	b.WriteString("    echo \"  PASS: $desc\"\n")
	b.WriteString("  else\n")
	b.WriteString("    FAIL=$((FAIL + 1))\n")
	b.WriteString("    echo \"  FAIL: $desc (got rejected status $rejected)\"\n")
	b.WriteString("  fi\n")
	b.WriteString("}\n\n")
}

// writeScriptFooter writes the summary and exit code.
func writeScriptFooter(b *strings.Builder, count int) {
	b.WriteString("# ── Summary ──\n\n")
	b.WriteString("echo \"\"\n")
	fmt.Fprintf(b, "echo \"Security Tests: $TOTAL total, $PASS passed, $FAIL failed (%d probes)\"\n", count)
	b.WriteString("if [ \"$FAIL\" -gt 0 ]; then\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n")
}

// writeAuthBypassTests probes auth-protected endpoints without a token and with a malformed token.
func writeAuthBypassTests(b *strings.Builder, app *ir.Application) int {
	count := 0
	authEndpoints := []*ir.Endpoint{}
	for _, ep := range app.APIs {
		if ep.Auth {
			authEndpoints = append(authEndpoints, ep)
		}
	}
	if len(authEndpoints) == 0 {
		return 0
	}

	b.WriteString("# ── 1. Auth Bypass ──\n")
	b.WriteString("echo \"[1/7] Auth Bypass\"\n\n")

	for _, ep := range authEndpoints {
		method := strings.ToUpper(httpMethod(ep.Name))
		path := apiPath(ep.Name)

		// Test without auth token
		fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s \"$BASE_URL%s\")\n", method, path)
		desc := fmt.Sprintf("%s %s without auth token", method, path)
		fmt.Fprintf(b, "assert_status '%s' 401 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
		count++

		// Test with malformed token
		fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s -H 'Authorization: Bearer invalid-token-xxx' \"$BASE_URL%s\")\n", method, path)
		desc = fmt.Sprintf("%s %s with malformed token", method, path)
		fmt.Fprintf(b, "assert_status '%s' 401 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
		count++
	}

	return count
}

// writeSQLInjectionTests sends SQL injection payloads to text parameters.
func writeSQLInjectionTests(b *strings.Builder, app *ir.Application) int {
	count := 0
	payloads := []string{
		"' OR '1'='1",
		"' UNION SELECT null--",
		"'; DROP TABLE users;--",
	}

	type textParam struct {
		ep    *ir.Endpoint
		param string
	}
	var targets []textParam
	for _, ep := range app.APIs {
		for _, p := range ep.Params {
			if isTextField(app, p.Name) {
				targets = append(targets, textParam{ep, p.Name})
			}
		}
	}
	if len(targets) == 0 {
		return 0
	}

	b.WriteString("# ── 2. SQL Injection ──\n")
	b.WriteString("echo \"[2/7] SQL Injection\"\n\n")

	for _, t := range targets {
		method := strings.ToUpper(httpMethod(t.ep.Name))
		path := apiPath(t.ep.Name)

		for _, payload := range payloads {
			body := curlJSONBody(map[string]string{t.param: payload})
			authHeader := ""
			if t.ep.Auth {
				authHeader = " -H 'Authorization: Bearer '\"$AUTH_TOKEN\""
			}
			fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s%s -H 'Content-Type: application/json' -d '%s' \"$BASE_URL%s\")\n",
				method, authHeader, shellEscapeSingleQuote(body), path)
			desc := fmt.Sprintf("SQLi on %s %s param %s", method, path, t.param)
			fmt.Fprintf(b, "assert_not_status '%s' 200 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
			count++
		}
	}

	return count
}

// writeXSSTests sends XSS payloads to text parameters.
func writeXSSTests(b *strings.Builder, app *ir.Application) int {
	count := 0
	payloads := []string{
		"<script>alert(1)</script>",
		"<img src=x onerror=alert(1)>",
		"javascript:alert(1)",
	}

	type textParam struct {
		ep    *ir.Endpoint
		param string
	}
	var targets []textParam
	for _, ep := range app.APIs {
		for _, p := range ep.Params {
			if isTextField(app, p.Name) {
				targets = append(targets, textParam{ep, p.Name})
			}
		}
	}
	if len(targets) == 0 {
		return 0
	}

	b.WriteString("# ── 3. XSS ──\n")
	b.WriteString("echo \"[3/7] XSS\"\n\n")

	for _, t := range targets {
		method := strings.ToUpper(httpMethod(t.ep.Name))
		path := apiPath(t.ep.Name)

		for _, payload := range payloads {
			body := curlJSONBody(map[string]string{t.param: payload})
			authHeader := ""
			if t.ep.Auth {
				authHeader = " -H 'Authorization: Bearer '\"$AUTH_TOKEN\""
			}
			fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s%s -H 'Content-Type: application/json' -d '%s' \"$BASE_URL%s\")\n",
				method, authHeader, shellEscapeSingleQuote(body), path)
			desc := fmt.Sprintf("XSS on %s %s param %s", method, path, t.param)
			fmt.Fprintf(b, "assert_not_status '%s' 200 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
			count++
		}
	}

	return count
}

// writeValidationBypassTests sends rule-violating values to validated endpoints.
func writeValidationBypassTests(b *strings.Builder, app *ir.Application) int {
	count := 0
	type valTarget struct {
		ep   *ir.Endpoint
		rule *ir.ValidationRule
	}
	var targets []valTarget
	for _, ep := range app.APIs {
		for _, v := range ep.Validation {
			targets = append(targets, valTarget{ep, v})
		}
	}
	if len(targets) == 0 {
		return 0
	}

	b.WriteString("# ── 4. Validation Bypass ──\n")
	b.WriteString("echo \"[4/7] Validation Bypass\"\n\n")

	for _, t := range targets {
		method := strings.ToUpper(httpMethod(t.ep.Name))
		path := apiPath(t.ep.Name)
		badValue := bashInvalidValue(t.rule)

		fields := map[string]string{}
		for _, p := range t.ep.Params {
			name := sanitizeParamName(p.Name)
			if strings.EqualFold(name, sanitizeParamName(t.rule.Field)) {
				fields[name] = badValue
			} else {
				fields[name] = "valid-" + name
			}
		}
		body := curlJSONBody(fields)
		authHeader := ""
		if t.ep.Auth {
			authHeader = " -H 'Authorization: Bearer '\"$AUTH_TOKEN\""
		}
		fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s%s -H 'Content-Type: application/json' -d '%s' \"$BASE_URL%s\")\n",
			method, authHeader, shellEscapeSingleQuote(body), path)
		desc := fmt.Sprintf("Validation bypass %s %s field %s (%s)", method, path, t.rule.Field, t.rule.Rule)
		fmt.Fprintf(b, "assert_status '%s' 400 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
		count++
	}

	return count
}

// writeIDORTests sends a foreign resource ID to endpoints with fetch steps.
func writeIDORTests(b *strings.Builder, app *ir.Application) int {
	count := 0
	var fetchEndpoints []*ir.Endpoint
	for _, ep := range app.APIs {
		for _, step := range ep.Steps {
			if step.Type == "query" {
				fetchEndpoints = append(fetchEndpoints, ep)
				break
			}
		}
	}
	if len(fetchEndpoints) == 0 {
		return 0
	}

	b.WriteString("# ── 5. IDOR ──\n")
	b.WriteString("echo \"[5/7] IDOR\"\n\n")

	for _, ep := range fetchEndpoints {
		method := strings.ToUpper(httpMethod(ep.Name))
		path := apiPath(ep.Name)
		// Append a foreign resource ID
		testPath := path + "/99999"
		authHeader := ""
		if ep.Auth {
			authHeader = " -H 'Authorization: Bearer '\"$AUTH_TOKEN\""
		}
		fmt.Fprintf(b, "STATUS=$(curl -s -o /dev/null -w '%%{http_code}' -X %s%s \"$BASE_URL%s\")\n",
			method, authHeader, testPath)
		desc := fmt.Sprintf("IDOR on %s %s with foreign ID", method, path)
		fmt.Fprintf(b, "assert_not_status '%s' 200 \"$STATUS\"\n\n", shellEscapeSingleQuote(desc))
		count++
	}

	return count
}

// writeRateLimitTests sends 120 rapid requests to check for rate limiting.
// Only generated if the app has rate limit rules.
func writeRateLimitTests(b *strings.Builder, app *ir.Application) int {
	if !hasRateLimitRule(app) {
		return 0
	}

	// Find the first GET endpoint
	var target *ir.Endpoint
	for _, ep := range app.APIs {
		if strings.ToUpper(httpMethod(ep.Name)) == "GET" {
			target = ep
			break
		}
	}
	if target == nil {
		return 0
	}

	path := apiPath(target.Name)

	b.WriteString("# ── 6. Rate Limiting ──\n")
	b.WriteString("echo \"[6/7] Rate Limiting\"\n\n")

	b.WriteString("RATE_LIMITED=0\n")
	b.WriteString("for i in $(seq 1 120); do\n")
	fmt.Fprintf(b, "  STATUS=$(curl -s -o /dev/null -w '%%{http_code}' \"$BASE_URL%s\")\n", path)
	b.WriteString("  if [ \"$STATUS\" -eq 429 ]; then\n")
	b.WriteString("    RATE_LIMITED=1\n")
	b.WriteString("    break\n")
	b.WriteString("  fi\n")
	b.WriteString("done\n")
	b.WriteString("TOTAL=$((TOTAL + 1))\n")
	b.WriteString("if [ \"$RATE_LIMITED\" -eq 1 ]; then\n")
	b.WriteString("  PASS=$((PASS + 1))\n")
	fmt.Fprintf(b, "  echo \"  PASS: Rate limiting active on GET %s\"\n", path)
	b.WriteString("else\n")
	b.WriteString("  FAIL=$((FAIL + 1))\n")
	fmt.Fprintf(b, "  echo \"  FAIL: No 429 after 120 requests to GET %s\"\n", path)
	b.WriteString("fi\n\n")

	return 1
}

// writeCORSTests sends an OPTIONS preflight from an evil origin.
func writeCORSTests(b *strings.Builder, app *ir.Application) int {
	if len(app.APIs) == 0 {
		return 0
	}

	path := apiPath(app.APIs[0].Name)

	b.WriteString("# ── 7. CORS ──\n")
	b.WriteString("echo \"[7/7] CORS\"\n\n")

	fmt.Fprintf(b, "CORS_RESP=$(curl -s -D - -o /dev/null -X OPTIONS -H 'Origin: http://evil.example.com' -H 'Access-Control-Request-Method: POST' \"$BASE_URL%s\")\n", path)
	b.WriteString("TOTAL=$((TOTAL + 1))\n")
	b.WriteString("if echo \"$CORS_RESP\" | grep -qi 'access-control-allow-origin: \\*'; then\n")
	b.WriteString("  FAIL=$((FAIL + 1))\n")
	b.WriteString("  echo \"  FAIL: CORS allows wildcard origin\"\n")
	b.WriteString("else\n")
	b.WriteString("  PASS=$((PASS + 1))\n")
	b.WriteString("  echo \"  PASS: CORS does not allow wildcard origin\"\n")
	b.WriteString("fi\n\n")

	return 1
}

// hasRateLimitRule checks if the app has any rate-limit related auth rules.
func hasRateLimitRule(app *ir.Application) bool {
	if app.Auth == nil {
		return false
	}
	for _, rule := range app.Auth.Rules {
		if strings.Contains(strings.ToLower(rule.Text), "rate limit") {
			return true
		}
	}
	return false
}

// bashInvalidValue returns a raw string value that should violate the given validation rule.
func bashInvalidValue(v *ir.ValidationRule) string {
	switch v.Rule {
	case "not_empty":
		return ""
	case "valid_email":
		return "not-an-email"
	case "min_length":
		return "x"
	case "max_length":
		return strings.Repeat("x", 300)
	case "unique":
		return "existing@example.com"
	case "future_date":
		return "2020-01-01"
	default:
		return "invalid"
	}
}

// shellEscapeSingleQuote escapes single quotes for safe use inside single-quoted bash strings.
func shellEscapeSingleQuote(s string) string {
	return strings.ReplaceAll(s, "'", `'\''`)
}

// curlJSONBody builds a JSON object string from a field map.
func curlJSONBody(fields map[string]string) string {
	if len(fields) == 0 {
		return "{}"
	}
	parts := make([]string, 0, len(fields))
	for k, v := range fields {
		escaped := strings.ReplaceAll(v, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		parts = append(parts, fmt.Sprintf(`"%s":"%s"`, k, escaped))
	}
	return "{" + strings.Join(parts, ",") + "}"
}

// renderSecurityTestSection produces a markdown section about the security test script.
func renderSecurityTestSection(count int) string {
	var b strings.Builder
	b.WriteString("## Security Probes\n\n")
	fmt.Fprintf(&b, "Generated **%d** runtime security probes in `security-tests.sh`.\n\n", count)
	b.WriteString("Run against a live instance:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("./security-tests.sh http://localhost:3001\n")
	b.WriteString("# With auth token:\n")
	b.WriteString("./security-tests.sh http://localhost:3001 \"your-jwt-token\"\n")
	b.WriteString("```\n\n")
	b.WriteString("Categories tested: Auth Bypass, SQL Injection, XSS, Validation Bypass, IDOR, Rate Limiting, CORS.\n\n")
	return b.String()
}
